#!/system/bin/sh

# ArchiDroid RunOnce (Backend) Script
# JustArchi@JustArchi.net

# Not Disabled
#exit 0

# Initial variables, you should NOT change them unless you know what you're doing
AD="/data/media/0/MrturDroid"
LOG="$AD/RunOnce.log" # "/dev/null" is no verbose
ADSTATUS="/dev/ARCHIDROID_RUNONCE_STATUS"

if [ ! -e $ADSTATUS ]; then
	# First boot, good
	echo -n $$ > $ADSTATUS
else
	ADSIGNAL=`cat $ADSTATUS`
	if [ $ADSIGNAL == "FINISHED" ]; then
		# Something tried to execute already finished init, halt
		echo "This script has been executed already"
		exit 0
	else
		kill -s 0 $ADSIGNAL >/dev/null 2>&1
		ADSIGNAL=$?
		if [ $ADSIGNAL -eq 0 ]; then
			# Something tried to execute already running init, double-execution?
			exit 3
		else
			# Old PID is dead and didn't exit properly, it looks like init re-executed itself f.e. for background purpose, allow that
			echo -n $$ > $ADSTATUS
		fi
	fi
fi

# Redirect stderr to our log, just in case something bad happen
#exec 1>$LOG # Use "exec 1>>$LOG" for append
echo -n "" > $LOG
exec 2>>$LOG

ADARGS() {
	# $1 - what we're looking for
	# $2 - where we're looking for
	if [ ! -z `echo "$2" | grep -i "$1"` ]; then
		return 0
	else
		return 1
	fi
}

DBUPDATE() {
	# Thanks to idcrisis, modified by JustArchi
	local DONE=0
	local TRY=0
	local SQLITE3='/system/xbin/sqlite3'
	local VAL1=""
	local VAL2=""
	local ID=""
	
	while [ $DONE -ne 1 ] ; do
		TRY=`expr $TRY + 1`
		if [ "$4" == "APPEND" ]; then
			# Append mode, value should exist already then
			VAL1=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null`
			VAL1=$VAL1$5$3
			
			# Let's update it now
			$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "update $1 set value='$VAL1' where name='$2';" 2>/dev/null
			
			# See if it worked
			VAL2=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null`
			
			if [ "$VAL1" == "$VAL2" ]; then
				# Looks good
				if [ $TRY -gt 1 ]; then
					echo "INFO: DBUPDATE APPEND SUCCEEDED with $@. It was our $TRY try" >> $LOG
				fi
				DONE=1
				return 0
			else
				# We failed, let's try maximum of 5 times before giving up
				echo "WARNING: DBUPDATE APPEND FAILED with $@. This is our $TRY try" >> $LOG
				sleep 1
				if [ $TRY -ge 5 ]; then
					echo "ERROR: Could not update $@ after $TRY times. I'm giving up here, please investigate!" >> $LOG
					DONE=1
					return 1
				fi
			fi
		else
			# Try to update value first if exists
			busybox sync
			$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "update $1 set value='$3' where name='$2';" 2>/dev/null
			busybox sync
			
			# See if it worked
			VAL1=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null`
			
			# If not create it
			if [ "$VAL1" != "" ]; then
				# Looks good
				DONE=1
				return 0
			else
				#ID=`sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select max(_id)+100 from $1;"`
				#if [ "$ID" == "" ]; then 
				#	ID='null'
				#fi
				ID='null'

				$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "insert into $1 values($ID, '$2', '$3');" 2>/dev/null
				busybox sync
			fi
			
			# Check if in fact we modified that
			VAL1=`$SQLITE3 /data/data/com.android.providers.settings/databases/settings.db "select value from $1 where name='$2';" 2>/dev/null`
			if [ "$VAL1" != "" ]; then
				# Looks good
				if [ $TRY -gt 1 ]; then
					echo "INFO: DBUPDATE SUCCEEDED with $@. It was our $TRY try" >> $LOG
				fi
				DONE=1
				return 0
			else
				# We failed, let's try maximum of 5 times before giving up
				echo "WARNING: DBUPDATE FAILED with $@. This is our $TRY try" >> $LOG
				sleep 1
				if [ $TRY -ge 5 ]; then
					echo "ERROR: Could not update $@ after $TRY times. I'm giving up here, please investigate!" >> $LOG
					DONE=1
					return 1
				fi
			fi
		fi
	done
}

# Parse args to variables
if ADARGS "background" "$@" ; then
	BACKGROUND=1
else
	BACKGROUND=0
fi
if ADARGS "forcedsemaphore" "$@" ; then
	FORCEDSEMAPHORE=1
else
	FORCEDSEMAPHORE=0
fi

echo "`date`" >> $LOG
echo "`uname -a`" >> $LOG
echo "INFO: ArchiDroid_RunOnce executed!" >> $LOG

# Now we need to make sure that this is background process to prevent slowing down bootup
if [ $BACKGROUND -ne 1 ]; then
	# We're not running in background, let's start a child and tell him that he's running in background
	echo "INFO: Spawning child!" >> $LOG
	sh $0 "background" &

	# Nothing to do here anymore, exit call
	exit 1
else
	# We're running in background so let's proceed
	echo "INFO: I'm a child!" >> $LOG
fi

# mrtur presset?
SAMMY=1
if [ -e /system/etc/mrtur.txt ]; then
SAMMY=0
fi

# We don't need to reload anything for now
ADRELOAD=0

# Don't force install mode, unless FORCE file exists
if [ -e $AD/FORCE ]; then
	echo "WARNING: Forcing Install mode, even if Update mode found!" >> $LOG
	FORCE=1
else
	echo "INFO: Not forcing Install mode if Update mode found" >> $LOG
	FORCE=0
fi

# We want some sqlite3 updates and settings but only if INSTALL mode is enabled
if [ -e $AD/INSTALL ] || [ $FORCE -eq 1 ]; then
	echo "INFO: Install mode detected, I'm either after full wipe or forced to think so. Turning on ADMANY and DBUPDATE" >> $LOG
	INSTALLMODE=1
	if [ -d $AD/FIRSTBOOT/DATA ]; then
		ADMANY=0
		cd $AD/FIRSTBOOT/DATA
		for folder in `busybox find . -mindepth 1 -maxdepth 1 -type d` ; do
			echo "I found $folder which need merging (data)" >> $LOG
			ADMANY=`expr $ADMANY + 1`
		done
	else
		ADMANY=0
	fi
	echo "INFO: I found $ADMANY folders which need merging (data)" >> $LOG
	DBUPDATE=1
	ADRELOAD=1
elif [ -e $AD/UPDATE ]; then
	echo "INFO: Update mode detected. Turning off ADMANY and DBUPDATE" >> $LOG
	INSTALLMODE=0
	DBUPDATE=0
	ADMANY=0
else
	# Panic
	echo "FATAL ERROR: Could not detect Install/Update mode, ABORTING RUNONCE, PLEASE INVESTIGATE" >> $LOG
	sysrw || mount -o remount,rw /system
	rm -f $0
	sysro || mount -o remount,ro /system

	# Init depends on us
	sh /system/etc/init.d/99ArchiDroid_Init "background" "force" &
	
	exit 2
fi

rm -f $AD/RunOnce.log.0



# ArchiDroid Semaphore
# Wait until we see some android processes to consider boot is more or less complete (credits to AndiP71)
# Also respect number of loops, maybe something went wrong
echo "INFO: RunOnce Semaphore started" >> $LOG
LOOP=0
while (! pgrep com.android && [ $LOOP -lt 150 ]) || [ $FORCEDSEMAPHORE -eq 1 ] ; do


	
	if [ $DBUPDATE -eq 1 ]; then
		if [ -e /data/data/com.android.providers.settings/databases/settings.db ]; then
			echo "INFO: Android created settings.db for me, how cute! Performing DBUPDATE" >> $LOG

			# Let's update selected keyboard according to our choice
			# TODO: We should handle this internally, according to FIRSTBOOT instead of hardcoding keyboards
			ONESHOT=1
			for KEYBOARDFULL in "org.pocketworkstation.pckeyboard/.LatinIME" "com.cootek.smartinputv5/com.cootek.smartinput5.TouchPalIME" "com.google.android.googlequicksearchbox/com.google.android.voicesearch.ime.VoiceInputMethodService" ; do
				KEYBOARD=`echo $KEYBOARDFULL | cut -d '/' -f 1`
				if [ -e /data/data/$KEYBOARD ] && [ $ONESHOT -eq 1 ]; then
					echo "INFO: $KEYBOARD Keyboard found!" >> $LOG
					DBUPDATE secure default_input_method "$KEYBOARDFULL"
					DBUPDATE secure enabled_input_methods "$KEYBOARDFULL"
					ONESHOT=0
				elif [ -e /data/data/$KEYBOARD ]; then
					echo "INFO: Additional $KEYBOARD Keyboard found!" >> $LOG
					#DBUPDATE secure enabled_input_methods "$KEYBOARDFULL" APPEND ":"
				fi
			done

			if [ $SAMMY -eq 1 ]; then
				echo "INFO: Applying standard preset DBUPDATE" >> $LOG
			#DBUPDATE system notification_sound 'content://media/internal/audio/media/32'
			#DBUPDATE system ringtone 'content://media/internal/audio/media/42'				
			#DBUPDATE secure advanced_reboot 1
			DBUPDATE secure ui_theme_mode 2			
			DBUPDATE global transition_animation_scale 0.0
			DBUPDATE global animator_duration_scale 0.0
			DBUPDATE global window_animation_scale 0.0
			DBUPDATE global wifi_scan_always_enabled 0
			DBUPDATE global install_non_market_apps 1
			DBUPDATE global package_verifier_enable 0			
			DBUPDATE system haptic_feedback_enabled 0
			#DBUPDATE system power_menu_screenshot_enabled 1
			DBUPDATE system status_bar_battery 1
			DBUPDATE system screen_off_timeout 30000			
			#DBUPDATE system statusbar_clock_date_display 1
			#DBUPDATE system statusbar_clock_date_format 'EEE dd MMM'
			#DBUPDATE system statusbar_clock_date_style 2
			#DBUPDATE system statusbar_clock_style 1
			#DBUPDATE global adb_enabled 1
			#DBUPDATE global development_settings_enabled 1
			#DBUPDATE secure lockscreen_frame_color -2
			#DBUPDATE secure lockscreen_lock_color -2
			#DBUPDATE secure lockscreen_dots_color -2
			DBUPDATE secure lockscreen_lock_icon '/data/data/com.android.settings/files/lock_icon1388332024286.png'
			DBUPDATE system notification_alpha 0.0
			DBUPDATE system power_menu_config '**poweroff**|empty|**reboot**|empty|**screenshot**|empty|**sound**|empty'
			DBUPDATE system navigation_bar_config '**recents**|**null**|empty|**home**|**null**|empty|**back**|**null**|empty'
			DBUPDATE system navigation_bar_height 60
			DBUPDATE system navigation_bar_width 60
			
			else
				echo "INFO: Applying mrtur preset DBUPDATE" >> $LOG
				
			# ==== mrtur =====
			DBUPDATE global adb_enabled 1
			DBUPDATE global airplane_mode_on 0
			DBUPDATE global animator_duration_scale 0.0
			DBUPDATE global assisted_gps_enabled 1
			#DBUPDATE global audio_safe_volume_state 3
			#DBUPDATE global auto_time 1
			#DBUPDATE global auto_time_zone 1
			DBUPDATE global bluetooth_on 1
			DBUPDATE global call_auto_retry 0
			#DBUPDATE global cdma_cell_broadcast_sms 1
			DBUPDATE global data_roaming 0
			#DBUPDATE global default_install_location 0
			#DBUPDATE global development_settings_enabled 1
			#DBUPDATE global device_provisioned 1
			DBUPDATE global dock_audio_media_enabled 1
			DBUPDATE global dock_sounds_enabled 0
			DBUPDATE global emergency_tone 0
			DBUPDATE global install_non_market_apps 1
			DBUPDATE global mobile_data 1
			DBUPDATE global mode_ringer 2
			#DBUPDATE global netstats_enabled 1
			DBUPDATE global package_verifier_enable 0
			DBUPDATE global power_notifications_enabled 0
			DBUPDATE global power_notifications_vibrate 0
			DBUPDATE global power_sounds_enabled 1
			#DBUPDATE global preferred_network_mode 0
			#DBUPDATE global set_install_location 0
			DBUPDATE global stay_on_while_plugged_in 0
			DBUPDATE global transition_animation_scale 0.0
			DBUPDATE global usb_mass_storage_enabled 1
			#DBUPDATE global wifi_display_on 0
			#DBUPDATE global wifi_max_dhcp_retry_count 9
			#DBUPDATE global wifi_networks_available_notification_on 1
			#DBUPDATE global wifi_on 0
			DBUPDATE global wifi_scan_always_enabled 0
			#DBUPDATE global wifi_sleep_policy 2
			#DBUPDATE global wifi_watchdog_on 1
			DBUPDATE global window_animation_scale 0.0
			#DBUPDATE secure accessibility_display_magnification_auto_update 1
			#DBUPDATE secure accessibility_display_magnification_enabled 0
			#DBUPDATE secure accessibility_display_magnification_scale 2.0
			#DBUPDATE secure accessibility_script_injection 0
			#DBUPDATE secure adb_port '-1'
			DBUPDATE secure advanced_reboot 1
			#DBUPDATE secure backup_enabled 0
			#DBUPDATE secure bluetooth_addr_valid 1
			#DBUPDATE secure dialpad_autocomplete 1
			DBUPDATE secure incall_power_button_behavior 2
			#DBUPDATE secure input_methods_subtype_history
			#DBUPDATE secure location_providers_allowed 'gps,network'
			#DBUPDATE secure lock_screen_appwidget_ids 2
			#DBUPDATE secure lock_screen_owner_info_enabled 0
			#DBUPDATE secure lockscreen.disabled 0
			DBUPDATE secure long_press_timeout 500
			#DBUPDATE secure mock_location 0
			#DBUPDATE secure mount_play_not_snd 1
			#DBUPDATE secure mount_ums_autostart 0
			#DBUPDATE secure mount_ums_notify_enabled 1
			#DBUPDATE secure mount_ums_prompt 1
			#DBUPDATE secure screensaver_activate_on_dock 1
			#DBUPDATE secure screensaver_activate_on_sleep 0
			#DBUPDATE secure screensaver_enabled 1
			#DBUPDATE secure selected_input_method_subtype '-1'
			#DBUPDATE secure selected_spell_checker_subtype 0
			#DBUPDATE secure speak_password 0
			#DBUPDATE secure touch_exploration_enabled 0
			DBUPDATE secure ui_theme_mode 2
			#DBUPDATE secure user_setup_complete 1
			DBUPDATE system accelerometer_rotation 0
			DBUPDATE system auto_brightness_backlight 14,28,37,51,71,80,96,108,255,255,255,255
			DBUPDATE system auto_brightness_lux 10,50,100,200,400,500,800,1000,1600,3000,10000
			DBUPDATE system auto_brightness_responsiveness 1.0
			DBUPDATE system dim_screen 1
			#DBUPDATE system dtmf_tone 0
			#DBUPDATE system dtmf_tone_type 0
			#DBUPDATE system expanded_desktop_mode 1
			#DBUPDATE system expanded_desktop_state 0
			DBUPDATE system haptic_feedback_enabled 0
			#DBUPDATE system hearing_aid 0
			#DBUPDATE system hide_rotation_lock_toggle_for_accessibility 1
			#DBUPDATE system hide_statusbar 0
			DBUPDATE system lock_volume_keys 1
			DBUPDATE system lockscreen_sounds_enabled 0
			DBUPDATE system menu_location 2
			DBUPDATE system menu_visibility 0
			#DBUPDATE system mode_ringer_streams_affected 166
			#DBUPDATE system mute_streams_affected 46
			#DBUPDATE system navigation_bar_alpha 0.0
			#DBUPDATE system navigation_bar_button_alpha 0.5
			#DBUPDATE system navigation_bar_glow_duration_off 10
			#DBUPDATE system navigation_bar_glow_duration_on 100
			DBUPDATE system navigation_bar_height 60
			DBUPDATE system navigation_bar_width 60
			#DBUPDATE system next_alarm_formatted
			#DBUPDATE system noise_suppression 0
			#DBUPDATE system notif_alpha 0.0
			#DBUPDATE system notif_wallpaper_alpha 0.1
			#DBUPDATE system notification_light_pulse 1
			#DBUPDATE system pie_background_alpha 1.0
			#DBUPDATE system pie_button_alpha 0.45
			#DBUPDATE system pie_button_color '-16777216'
			#DBUPDATE system pie_button_pressed_alpha 1.0
			#DBUPDATE system pie_button_pressed_color '-16777216'
			#DBUPDATE system pie_buttons_config '**expanded_desktop**|**null**|empty|**home**|**null**|empty|**recents**|**null**|empty|**back**|**null**|empty'
			#DBUPDATE system pie_controls 1
			#DBUPDATE system pie_disable_statusbar_info 0
			#DBUPDATE system pie_gravity 6
			#DBUPDATE system pie_icon_color '-13388315'
			#DBUPDATE system pie_show_snap 0
			#DBUPDATE system pie_show_text 0
			#DBUPDATE system pie_size 1.5
			#DBUPDATE system pie_snap_color '-16777216'
			#DBUPDATE system pie_softkeyboard_is_showing 0
			#DBUPDATE system pie_text_color '-13388315'
			#DBUPDATE system pie_trigger_gravity_left_right 80
			#DBUPDATE system pie_trigger_height 0.68
			#DBUPDATE system pie_trigger_show 0
			#DBUPDATE system pie_trigger_thickness 13.5
			#DBUPDATE system pointer_speed 0
			#DBUPDATE system power_menu_airplane_enabled 0
			#DBUPDATE system power_menu_expanded_desktop_enabled 1
			#DBUPDATE system power_menu_screenshot_enabled 1
			DBUPDATE system power_menu_config '**poweroff**|empty|**reboot**|empty|**screenshot**|empty|**sound**|empty'			
			DBUPDATE system power_ui_low_battery_warning_policy 1
			#DBUPDATE system quick_settings_tile_content
			#DBUPDATE system radio.data.stall.recovery.action 0
			DBUPDATE system recents_clear_all_on_right 1
			#DBUPDATE system screen_brightness 87
			#DBUPDATE system screen_brightness_mode 1
			DBUPDATE system screen_off_timeout 30000
			DBUPDATE system sound_effects_enabled 0
			#DBUPDATE system status_bar_alpha 0.85
			DBUPDATE system status_bar_battery 1
			DBUPDATE system statusbar_clock_date_display 1
			DBUPDATE system statusbar_clock_date_format 'EEE dd MMM'
			DBUPDATE system statusbar_clock_date_style 2
			DBUPDATE system statusbar_clock_style 1
			DBUPDATE system system_power_enable_crt_off 0
			DBUPDATE system system_profiles_enabled 0
			DBUPDATE system navigation_bar_config '**recents**|**null**|empty|**home**|**null**|empty|**back**|**null**|empty'			
			#DBUPDATE system tablet_ui 0
			#DBUPDATE system toggle_notification_and_qs_shade 0
			DBUPDATE system transition_animation_scale 1.0
			#DBUPDATE system tty_mode 0
			#DBUPDATE system ui_force_overflow_button 0
			DBUPDATE system user_rotation 0
			DBUPDATE system vibrate_when_ringing 1
			#DBUPDATE system volume_alarm 6
			#DBUPDATE system volume_bluetooth_sco 7
			#DBUPDATE system volume_music 11
			#DBUPDATE system volume_music_headphone 7
			#DBUPDATE system volume_music_headset 7
			#DBUPDATE system volume_notification 5
			#DBUPDATE system volume_ring 5
			#DBUPDATE system volume_system 7
			#DBUPDATE system volume_voice 4
			DBUPDATE system wakeup_when_plugged_unplugged 0
			DBUPDATE system window_animation_scale 1.0
			#DBUPDATE system notification_sound 'content://media/internal/audio/media/32'
			DBUPDATE system ringtone 'content://media/internal/audio/media/21'
			
			fi
			
			# And don't execute twice
			echo "INFO: Finished DBUPDATE" >> $LOG
			DBUPDATE=0
		fi
	fi
	
	# Now let's MAKE SURE that our settings are in fact applied, only if we don't have shared_prefs already (prevent non-clean override)
	if [ $ADMANY -gt 0 ]; then
		cd $AD/FIRSTBOOT/DATA
		for FOLDER in * ; do
			if [ -d /data/data/$FOLDER ]; then
				echo "INFO: I'm currently merging $FOLDER, called by ADMANY" >> $LOG
				ADOWNER=`busybox ls -ld /data/data/$FOLDER | awk '{print $3}'`
				cp -R $FOLDER/* /data/data/$FOLDER/
				busybox chown -hR $ADOWNER.$ADOWNER /data/data/$FOLDER
				#busybox chmod -R 777 /data/data/$FOLDER

				# Let's make it as safe as possible
				cd /data/data/$FOLDER
				for FILE in `busybox find . -type d -mindepth 1`; do
					busybox chmod 775 $FILE
				done
				for FILE in `busybox find . -type f -mindepth 1`; do
					EXTENSION=`echo $FILE | awk -F '.' '{print $NF}'`

					# Try to apply correct permissions for specific files
					# For example XposedBridge requires at least 644, so it doesn't work with generic 660
					case "$EXTENSION" in
						"jar")
							busybox chmod 664 $FILE
							;;
						*)
							busybox chmod 666 $FILE
					esac
				done

				cd $AD/FIRSTBOOT/DATA
				# And we're done!
				rm -Rf $FOLDER
				rm -Rf /data/data/$FOLDER/_ADTEMP
				ADOWNER=""
				ADMANY=`expr $ADMANY - 1`
				echo "INFO: Done! $ADMANY to go" >> $LOG
			fi
		done
	fi

	# Sleeping time
	FORCEDSEMAPHORE=0
	LOOP=`expr $LOOP + 1`
	sleep 2
done

if [ $LOOP -ge 150 ]; then
	echo "ERROR: I looped $LOOP times and needed to exit from infinite loop, not good (RunOnce Semaphore)" >> $LOG
elif [ $LOOP -eq 0 ]; then
	echo "ERROR: I didn't even entered semaphore, forcing it this time, it may cause unexpected behaviour!" >> $LOG
	sh $0 "background" "forcedsemaphore" &
	exit 3
else
	echo "INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (RunOnce Semaphore)" >> $LOG
fi

# Post-Installation functions
if [ $INSTALLMODE -eq 1 ]; then
	echo "INFO: Calling Post-Installation functions (if any)" >> $LOG
fi

# I'm runonce script so let's clean everything and delete myself

rm -f $AD/INSTALL
rm -f $AD/UPDATE
rm -f $AD/FORCE
rm -Rf $AD/FIRSTBOOT

sysrw || mount -o remount,rw /system
rm -f $0
busybox sync
#sysro || mount -o remount,ro /system

if [ ! -e "$0" ]; then
	echo "INFO: Could not detect RunOnce in init.d after cleanup, that's good" >> $LOG
else
	echo "ERROR: I've detected RunOnce still in init.d after cleanup, that's not good, please investigate" >> $LOG
fi

# Execute a reboot if we need it
if [ $ADRELOAD -eq 1 ]; then
	echo "INFO: Reboot required, I'm rebooting the device right now" >> $LOG

	echo "INFO: ArchiDroid RunOnce finished" >> $LOG
	echo "`date`" >> $LOG
	busybox sync
	reboot
	#killall system_server
	sleep 10
else
	# We should call Init if reboot isn't required
	sh /system/etc/init.d/99ArchiDroid_Init "background" "force" &

	sleep 20
	sysro || mount -o remount,ro /system
	# Finish
	echo "INFO: ArchiDroid RunOnce finished" >> $LOG
	echo "`date`" >> $LOG
	echo -n "FINISHED" > $ADSTATUS
fi
exit 0
